#!/bin/zsh
TMUX= 
tmux new-session -d -s mail 'ZSHINIT=mail zsh'
tmux new-session -d -s irc 'ZSHINIT=irc zsh'
if [ `hostname` = "bialobrewy" ]
then
	tmux new-session -d -s Imgur 'ZSHINIT=rails zsh'
	tmux new-session -d -s seriale 'ZSHINIT=seriale zsh'
	tmux new-session -d -s current 'ZSHINIT=current zsh'
	tmux new-session -d -s torrents 'ZSHINIT=torrents zsh'
elif [ `hostname` = "adeli" ]
then
	tmux new-session -d -s dev 'ZSHINIT=dev zsh'
fi
